# 테마 설정
theme: "minimal-mistakes-jekyll"

# 스킨 설정

minimal_mistakes_skin : "dark"

locale : "ko-KR"

title : "재혁 JAVA 실습"

title_separator : "-"

name : "Jae Hyuck Chang"

description : "장재혁, Java프로그래밍실습"

url : "https://jaehchangscsc.github.io/JavaClass/"


markdown : kramdown
highligher : rouge
